### ISSUE TITLE
Can't run default code since recent update

### ISSUE THREAD

**Issue by kirstytaggart** [FireflySpectra/firefly_release#1]
It seems like the changes to ```firefly_models.py``` might be causing issues since I can't get the most recent version to work on the test data (12 June 2020 version works fine for me). 

I think it might be because the default lib is set to ```E-MaStar```, But ```fluxgrid ``` is only assigned if ```lib=='gold'```.  This results in an error because its missing this:
``` flux = fluxgrid[ii,jj,sidx,:] ``` 
``` UnboundLocalError: local variable 'fluxgrid' referenced before assignment```

**Comment by jusneuma** [comment]
Thank you for raising the issue. That is correct, thanks for finding the bug. The default lib is not updated and should be set to `model_lib=['gold']`.
The new version of the MaStar models (>1.0) only include the 'gold' version, which is a replacement of Th-MaStar in version <1.0.

Please set `model_lib=['gold']` in `firefly.py` and `firefly_sdss.py`. The issue will be resolved in the next release.

**Comment by jusneuma** [comment]
Issue has been fixed in latest release.
