### ISSUE TITLE
Masking emission lines assumes air wavelengths

### ISSUE THREAD

**Issue by joannawooastro** [FireflySpectra/firefly_release#2]
When the data are given in vacuum wavelengths (data_wave_medium='vacuum'), the emission line masking is not centred on the emission lines.  I believe this is because the emission lines are defined in air wavelengths.  For small mask widths (eg ~ 8 Angstroms), this means that parts of the emission lines are not masked.

**Comment by jusneuma** [comment]
Thank you for pointing this out. This will be fixed in the next release, which will be online within the next few days.

**Comment by jusneuma** [comment]
Fixed in https://github.com/FireflySpectra/firefly_release/releases/tag/1.0.3

**Comment by jusneuma** [comment]
fixed in https://github.com/FireflySpectra/firefly_release/releases/tag/1.0.3
