### ISSUE TITLE
max_ebv does not have desired effect

### ISSUE THREAD

**Issue by joannawooastro** [FireflySpectra/firefly_release#3]
When max_ebv=1.5 (the default in the example), the output E(B-V) values only go up to 0.67.  I dug into the code and I believe line 857 of firefly_dust.py is the culprit.  It should be corrected to:  

`ebv_arr     = SPM.max_ebv*np.arange(num_laws)/(num_laws - 1)`

in order to run from 0 to max_ebv.

**Comment by jusneuma** [comment]
Thanks for pointing out that issue. I agree. We will implement that fix asap.

**Comment by jusneuma** [comment]
fixed in https://github.com/FireflySpectra/firefly_release/releases/tag/1.0.3
